### ISSUE TITLE
Implement external plugins support API

### ISSUE THREAD

**Issue by stepango** [formatools/forma#35]

**Comment by michaem** [comment]
Need to make implementation for applying external plugins, like 
`apply(plugin = "androidx.navigation.safeargs.kotlin")`  into `:core:navigation:res module`.

Also necessary to take next requirements:
- applying custom plugins should be available on each target type
- applying semantic should be same as other Form DSL construction
- clearly for user (inboxing)
- support plugins configurations

**Comment by KarenkovID** [comment]
Add simple implementation #75
