### ISSUE TITLE
Client config providing

### ISSUE THREAD

**Issue by michaem** [formatools/forma#45]
Now api urls are located directly in `NetworkModule`, in`: core: network: library`
```
 Retrofit.Builder()
            .baseUrl("https://gateway.marvel.com/")
            .addConverterFactory(GsonConverterFactory.create())
            .build()
```
Necessary to make configs for sample application for putting url, api versions and other transport information there. After pass these configs to component modules, like `: core: network: library`

**Comment by ntnsmirnov** [comment]
@samokryl  "todo" is fogotten in "ServiceMarvelRepository"
