### ISSUE TITLE
Support ViewBinding

### ISSUE THREAD

**Issue by KarenkovID** [formatools/forma#72]
Now we have support of dataBinding (contains viewBinding). We can't use Kotlin synthetic in deferent modules and it is deprecated since Kotlin 1.4.20. Need to add support of viewBinding

**Comment by michaem** [comment]
You can do it easy by:
- adding additional target `viewBinding` (as dataBinding)
- `viewBinding` field to Forma class.
- turn on view binding in AndroidBinaryFeatureConfiguration by setting flag to true
