### ISSUE TITLE
No application changes occur when updating code / layout

### ISSUE THREAD

**Issue by tequilaonelove** [formatools/forma#87]
Я делал небольшой пример приложения с несколькими модулями. 
[https://github.com/tequilaonelove/forma-sample.git](https://github.com/tequilaonelove/forma-sample.git)
Столкнулся с какой-то странной проблемой. 

При обновлении кода или макета, изменений в приложении не происходит. Например если внести какие-либо изменения в `layout/activity_main.xml`, например если убрать кнопку или поменять ей текст, то при последующем запуске на реальном устройстве `Run app` (Shift+F10) , - не происходит никаких изменений.

Чтобы произошли эти самые изменения, необходимо предварительно очистить весь кеш `Clean Project` и заново "сбилдить" проект. 

Это занимает достаточно большое время, для такого маленького изменения. Я оставил ссылку на репозиторий, где существует эта проблема, чтобы можно было её воспроизвести.

Перезагрузка Android Studio и `Invalidate Caches` не помогает..  Где-то я ошибся или что-то упустил..?

**Comment by tequilaonelove** [comment]
Может кто-нибудь посмотреть репозиторий с проблемой?

**Comment by KarenkovID** [comment]
Какую версию Android Studio вы используете? Изменения в activity_main.xml тут же отображаются при новой сборке. Единственная проблема: белый текст на белой кнопке на белом фоне. Если вы измените textColor = "#000000" то увидите изменения текста.

**Comment by tequilaonelove** [comment]
Версия Android Studio 4.1.2. То есть вы сделали изменения в activity_main.xml, дажее просто нажали `Run` и изменения произошли? Ух, спасибо за комментарий, буду тогда дальше искать источник проблемы (

**Comment by tequilaonelove** [comment]
Во вкладке `Run/Debug Configurations` зашел в конфигурацию `Android App` -> `binary` , и в пустой блок `Before launch` добавил конфигурацию `Gradle-aware Make` , после чего приложение стало нормально "пересобираться" и отображать все внесенные изменения. Проблему можно считать решенной :)
